### ISSUE TITLE
Package rename

### ISSUE THREAD

**Issue by ccordoba12** [spyder-ide/spyder-pyls#1]
We need to do these tasks in order to rename the package

- [x] Change package name in setup.py to `spyder-pyls`.
- [x] Change Readme to describe how to develop this package with Spyder.
- [x] Remove versioneer.py, add release instructions and add a tuple with the current version to `_version.py`.
- [x] Set initial version to 0.90 to differentiate from `python-language-server`.
- [x] Set CIs
- [x] Add changelog for version 0.90.
- [x] Remove old branches (except `develop`)

**Comment by goanpeca** [comment]
@ccordoba12 what do you mean by 

`Change Readme to describe how to develop this package with Spyder.` ?
