### ISSUE TITLE
Anaconda versus Spyder Language Server

### ISSUE THREAD

**Issue by ghost** [spyder-ide/spyder-pyls#15]
Are the Ananconda and Spyder language servers the same ?

**Comment by ccordoba12** [comment]
Why do you want to know? That's an internal implementation detail that users don't really need to know about.

**Comment by ccordoba12** [comment]
Besides, there's no Anaconda Language Server (still). There's a package maintained by us in conda-forge, that's all.

**Comment by ghost** [comment]
There is an Ananconda page and a Spyder page to install language server - with different commands for installing the packages. Running the install using conda will install it whereas using the pip instructions on the Spyder page results in a version not found error. The difference between conda-forge and spyder pyls is not an obvious one.

**Comment by ccordoba12** [comment]
> There is an Ananconda page and a Spyder page to install language server

What pages are you referring to?

> Running the install using conda will install it whereas using the pip instructions on the Spyder page results in a version not found error

We test our installation with both conda and pip and both are working as expected. So I don't understand your error. Please be more specific.

**Comment by ghost** [comment]
Following the insrtuctions (conda) on this page: https://anaconda.org/conda-forge/python-language-server

Results: https://imgur.com/a/FKkxw9Y

Following the instructions (pip) on this page: https://github.com/spyder-ide/spyder-pyls

Results: https://imgur.com/a/qFKofB2

**Comment by ccordoba12** [comment]
> Following the instructions (pip) on this page

I see. There's no public release of this package yet, so please use instead

    pip install python-language-server[all]

Also, the installation instructions for the Spyder master branch are clearly documented here:

https://github.com/spyder-ide/spyder/blob/master/CONTRIBUTING.md
